anchor_version = "0.25.0"

[programs.localnet]
rfq = "EYZVRgDAWHahx3bJXFms7CoPA6ncwJFkGFPiTa15X8Fk"
risk_engine = "AVauPJngjyumG2c2dRaGjdDPbrYwZLmV5iSTHAea4GXn"
spot_instrument = "FTzYU9cFnziCQvJ6ZUve7asaYqRexk7pBcn8zQ9MqoMQ"
psyoptions_european_instrument = "BeJcAotUcFEWXVnh6qaBBLKaZaoaM8HSFY1L3sb1Aps3"
psyoptions_american_instrument = "Cdaz7EGr2AVDkCpjMVEXDzap6oRrrrZUEaKAVLmJAX7R"

[programs.devnet]
rfq = "EYZVRgDAWHahx3bJXFms7CoPA6ncwJFkGFPiTa15X8Fk"
risk_engine = "AVauPJngjyumG2c2dRaGjdDPbrYwZLmV5iSTHAea4GXn"
spot_instrument = "FTzYU9cFnziCQvJ6ZUve7asaYqRexk7pBcn8zQ9MqoMQ"
psyoptions_european_instrument = "BeJcAotUcFEWXVnh6qaBBLKaZaoaM8HSFY1L3sb1Aps3"
psyoptions_american_instrument = "Cdaz7EGr2AVDkCpjMVEXDzap6oRrrrZUEaKAVLmJAX7R"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-american-instrument/program",
    "psyoptions-european-instrument/program"
]

