[programs.localnet]
rfq = "3UA1aU58WxePXwtLCMb1CGPQjQQFqVPoKsEQo8vMFe3q"
risk_engine = "E3mS5KjyhgZ5yP9ff3psQb7KsQfBJYTfiwGczE2kVN5R"
spot_instrument = "A5mS5KjyhgZ5yP9ff3psQb7KsQfBJYTfiwGczE2kVNMM"

[programs.devnet]
rfq = "3UA1aU58WxePXwtLCMb1CGPQjQQFqVPoKsEQo8vMFe3q"
risk_engine = "E3mS5KjyhgZ5yP9ff3psQb7KsQfBJYTfiwGczE2kVN5R"
spot_instrument = "A5mS5KjyhgZ5yP9ff3psQb7KsQfBJYTfiwGczE2kVNMM"

[programs.mainnet]
rfq = "3UA1aU58WxePXwtLCMb1CGPQjQQFqVPoKsEQo8vMFe3q"
risk_engine = "E3mS5KjyhgZ5yP9ff3psQb7KsQfBJYTfiwGczE2kVN5R"
spot_instrument = "A5mS5KjyhgZ5yP9ff3psQb7KsQfBJYTfiwGczE2kVNMM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
