[programs.localnet]
rfq = "GxT7mn3cmaJMvX2FjeabgUQozyGUELqqfQwsjM98aFtC"
risk_engine = "CZgrS2mXL6XKNq6uwboBZKWrUTezCVdrKEuiXSSN69GS"
spot_instrument = "DzqdNPDezykYX4TkM1CX1c1VdmZY9pjnRVt9v6W2iftv"
psyoptions_american_instrument = "GX3X7FB3c1UniCxmEYwbtdeizteEPXDdDvSJ198EdW3Z"

[programs.devnet]
rfq = "GxT7mn3cmaJMvX2FjeabgUQozyGUELqqfQwsjM98aFtC"
risk_engine = "CZgrS2mXL6XKNq6uwboBZKWrUTezCVdrKEuiXSSN69GS"
spot_instrument = "DzqdNPDezykYX4TkM1CX1c1VdmZY9pjnRVt9v6W2iftv"
psyoptions_american_instrument = "GX3X7FB3c1UniCxmEYwbtdeizteEPXDdDvSJ198EdW3Z"

[programs.mainnet]
rfq = "GxT7mn3cmaJMvX2FjeabgUQozyGUELqqfQwsjM98aFtC"
risk_engine = "CZgrS2mXL6XKNq6uwboBZKWrUTezCVdrKEuiXSSN69GS"
spot_instrument = "DzqdNPDezykYX4TkM1CX1c1VdmZY9pjnRVt9v6W2iftv"
psyoptions_american_instrument = "GX3X7FB3c1UniCxmEYwbtdeizteEPXDdDvSJ198EdW3Z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/convergence-v2.json"