[programs.localnet]
rfq = "47p5Rh3fDeWp8ejFxThZE2uSwkAoyySSRXLDGWzcic92"
       
[programs.devnet]
rfq = "47p5Rh3fDeWp8ejFxThZE2uSwkAoyySSRXLDGWzcic92"

[programs.mainnet]
rfq = "47p5Rh3fDeWp8ejFxThZE2uSwkAoyySSRXLDGWzcic92"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/rfq.spec.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/psyamerican.spec.ts"