anchor_version = "0.25.0"

[programs.localnet]
rfq = "J2rDyo2NpZn4FQ5rGXmdwh3i2y1h11ynodYrrcUxfErq"
risk_engine = "9sEUmfZPhH8qVEoFmfdbJhKcfWP5LCCZfb2Cu7zffs4b"
spot_instrument = "826r9RA3AGHPas5E4DgbN9MpYa8gE2ZDUPUJW6GEZ3cT"
psyoptions_european_instrument = "94sxcX64yqe1s7zY2Hx8tEN8tqisK86dASfizAKkxK7A"
psyoptions_american_instrument = "2XYQhTq6k3anvDSdiQ6hyNyzLS3m4TbAgokVr8EGAPHf"

[programs.devnet]
rfq = "J2rDyo2NpZn4FQ5rGXmdwh3i2y1h11ynodYrrcUxfErq"
risk_engine = "9sEUmfZPhH8qVEoFmfdbJhKcfWP5LCCZfb2Cu7zffs4b"
spot_instrument = "826r9RA3AGHPas5E4DgbN9MpYa8gE2ZDUPUJW6GEZ3cT"
psyoptions_european_instrument = "94sxcX64yqe1s7zY2Hx8tEN8tqisK86dASfizAKkxK7A"
psyoptions_american_instrument = "2XYQhTq6k3anvDSdiQ6hyNyzLS3m4TbAgokVr8EGAPHf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/convergence-v2.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-american-instrument/program",
    "psyoptions-european-instrument/program"
]
