[programs.localnet]
rfq = "2rPciaAyyvNKZV5fiabaC3Rsje16t6CqpPaL1pCVVX6M"
       
[programs.devnet]
rfq = "2rPciaAyyvNKZV5fiabaC3Rsje16t6CqpPaL1pCVVX6M"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/convergence.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"