anchor_version = "0.25.0"

[programs.localnet]
rfq = "BThK6bNFeBkMHphJ5bcUKi1tXWPyFqbFN4FKB7WoiJEU"

[programs.devnet]
rfq = "BThK6bNFeBkMHphJ5bcUKi1tXWPyFqbFN4FKB7WoiJEU"

[programs.mainnet]
rfq = "BThK6bNFeBkMHphJ5bcUKi1tXWPyFqbFN4FKB7WoiJEU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["rfq/program"]

[scripts]
generate-test-fixtures = "yarn ts-node -T tests/scripts/fixturesGenerator.ts"
