anchor_version = "0.28.0"

[programs.localnet]
rfq = "CdvjLpJGpYTdpdanPpfUe1zPERYvpvP4VALUz62eRrGP"
risk_engine = "GL6ezn1mYExqgbFQs85NjfBUi1k4uYkdjGf2pvSKktz8"
spot_instrument = "2LmfeVxwy5CqF5ufqfa6PVGRGjxJizEawQF1SngACufT"
psyoptions_european_instrument = "3cPrWr9jp8bHcVhH1dy6AKTyPS1yo6jQRoNmgPCcP2MM"
psyoptions_american_instrument = "8MvpZsBa4fRjRLR717CDQHzGEkvXr3anpQLpm9zDHY1G"
hxro_print_trade_provider = "GyRW7qvzx6UTVW9DkQGMy5f1rp9XK2x53FvWSjUUF7BJ"

[programs.devnet]
rfq = "CdvjLpJGpYTdpdanPpfUe1zPERYvpvP4VALUz62eRrGP"
risk_engine = "GL6ezn1mYExqgbFQs85NjfBUi1k4uYkdjGf2pvSKktz8"
spot_instrument = "2LmfeVxwy5CqF5ufqfa6PVGRGjxJizEawQF1SngACufT"
psyoptions_european_instrument = "3cPrWr9jp8bHcVhH1dy6AKTyPS1yo6jQRoNmgPCcP2MM"
psyoptions_american_instrument = "8MvpZsBa4fRjRLR717CDQHzGEkvXr3anpQLpm9zDHY1G"
hxro_print_trade_provider = "GyRW7qvzx6UTVW9DkQGMy5f1rp9XK2x53FvWSjUUF7BJ"

[programs.mainnet]
rfq = "CdvjLpJGpYTdpdanPpfUe1zPERYvpvP4VALUz62eRrGP"
risk_engine = "GL6ezn1mYExqgbFQs85NjfBUi1k4uYkdjGf2pvSKktz8"
spot_instrument = "2LmfeVxwy5CqF5ufqfa6PVGRGjxJizEawQF1SngACufT"
psyoptions_european_instrument = "3cPrWr9jp8bHcVhH1dy6AKTyPS1yo6jQRoNmgPCcP2MM"
psyoptions_american_instrument = "8MvpZsBa4fRjRLR717CDQHzGEkvXr3anpQLpm9zDHY1G"
hxro_print_trade_provider = "GyRW7qvzx6UTVW9DkQGMy5f1rp9XK2x53FvWSjUUF7BJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-european-instrument/program",
    "hxro-print-trade-provider/program",
    "psyoptions-american-instrument/program",
]

[scripts]
generate-test-fixtures = "yarn ts-node -T tests/scripts/fixturesGenerator.ts"
