anchor_version = "0.25.0"

[programs.localnet]
rfq = "J7WkE9mTzwTo3pjxENdrH7sekZPrN2VYNpk1pgfZxVr9"
risk_engine = "6rosVyXKwj9tiHubXUBTguaCELsci4pBEuiRy36Lbz1p"
spot_instrument = "CjQCEjXtG3QNBuT5Z1sctaAYCo5Mt6edftqHQetEPo9w"
psyoptions_european_instrument = "A86fhhdNVDdXV8pB48WXtPeM3EBkcBeJEdrx9xrUo9nF"
psyoptions_american_instrument = "6JG1tWK4w6LmjeXbmDZJsmUsPSjgnp74j2XPsTvjjTX8"

[programs.devnet]
rfq = "J7WkE9mTzwTo3pjxENdrH7sekZPrN2VYNpk1pgfZxVr9"
risk_engine = "6rosVyXKwj9tiHubXUBTguaCELsci4pBEuiRy36Lbz1p"
spot_instrument = "CjQCEjXtG3QNBuT5Z1sctaAYCo5Mt6edftqHQetEPo9w"
psyoptions_european_instrument = "A86fhhdNVDdXV8pB48WXtPeM3EBkcBeJEdrx9xrUo9nF"
psyoptions_american_instrument = "6JG1tWK4w6LmjeXbmDZJsmUsPSjgnp74j2XPsTvjjTX8"

[programs.mainnet]
rfq = "J7WkE9mTzwTo3pjxENdrH7sekZPrN2VYNpk1pgfZxVr9"
risk_engine = "6rosVyXKwj9tiHubXUBTguaCELsci4pBEuiRy36Lbz1p"
spot_instrument = "CjQCEjXtG3QNBuT5Z1sctaAYCo5Mt6edftqHQetEPo9w"
psyoptions_european_instrument = "A86fhhdNVDdXV8pB48WXtPeM3EBkcBeJEdrx9xrUo9nF"
psyoptions_american_instrument = "6JG1tWK4w6LmjeXbmDZJsmUsPSjgnp74j2XPsTvjjTX8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-european-instrument/program",
    "psyoptions-american-instrument/program",
]

[scripts]
generate-test-fixtures = "yarn ts-node -T tests/scripts/fixturesGenerator.ts"
