[programs.localnet]
rfq = "6k3nypehfxd4tqCGRxNEZBMiT4xUPdQCkothLVz3JK6D"
risk_engine = "76TdqS9cEb8tYKUWKMzXBMwgCtXJiYMcrHxmzrYthjUm"
spot_instrument = "6pyiZyPDi7a6vMymw5NFTvtFBZJbDrNsgrcYK5jGEH4K"
psyoptions_european_instrument = "7ZD9LcvMPfurRYz2AuZPWgtSXuSxPmvZNMBFK7fhyvQA"

[programs.devnet]
rfq = "6k3nypehfxd4tqCGRxNEZBMiT4xUPdQCkothLVz3JK6D"
risk_engine = "76TdqS9cEb8tYKUWKMzXBMwgCtXJiYMcrHxmzrYthjUm"
spot_instrument = "6pyiZyPDi7a6vMymw5NFTvtFBZJbDrNsgrcYK5jGEH4K"
psyoptions_european_instrument = "7ZD9LcvMPfurRYz2AuZPWgtSXuSxPmvZNMBFK7fhyvQA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-european-instrument/program",
]
