anchor_version = "0.28.0"


[programs.localnet]
rfq = "EMFRxsc7FSavsUVKuwNiywXixYthe2Mo5GUNaUvnvBva"
risk_engine = "F3o2hWqv61TavHuZYuStvW2Zd3M1JnoqBmmgGU77LRTr"
spot_instrument = "4A9M7iojGDPc4n4YDGnTmsYsNKUohG1zM1nrAqVMMmrm"
psyoptions_european_instrument = "6B7TdBNAF7tWWz5sZbbBZj8jH1ix7QWAchtkvMHveEuW"
psyoptions_american_instrument = "HGmSFSRfVAG8RC8Ae4G1JFSHK7Au5GrGskDxncG3JRok"
hxro_print_trade_provider = "4WbVwc5Edfo3oB1n16bVC9qrghYHSNh1qAECbSCyiT95"
vault_operator = "5Qnp9VdXtRvmR9wBcAdvqTRsBHzpZ4jU3ZKtn3BaYWUM"

[programs.devnet]
rfq = "EMFRxsc7FSavsUVKuwNiywXixYthe2Mo5GUNaUvnvBva"
risk_engine = "F3o2hWqv61TavHuZYuStvW2Zd3M1JnoqBmmgGU77LRTr"
spot_instrument = "4A9M7iojGDPc4n4YDGnTmsYsNKUohG1zM1nrAqVMMmrm"
psyoptions_european_instrument = "6B7TdBNAF7tWWz5sZbbBZj8jH1ix7QWAchtkvMHveEuW"
psyoptions_american_instrument = "HGmSFSRfVAG8RC8Ae4G1JFSHK7Au5GrGskDxncG3JRok"
hxro_print_trade_provider = "4WbVwc5Edfo3oB1n16bVC9qrghYHSNh1qAECbSCyiT95"
vault_operator = "5Qnp9VdXtRvmR9wBcAdvqTRsBHzpZ4jU3ZKtn3BaYWUM"

[programs.mainnet]
rfq = "EMFRxsc7FSavsUVKuwNiywXixYthe2Mo5GUNaUvnvBva"
risk_engine = "F3o2hWqv61TavHuZYuStvW2Zd3M1JnoqBmmgGU77LRTr"
spot_instrument = "4A9M7iojGDPc4n4YDGnTmsYsNKUohG1zM1nrAqVMMmrm"
psyoptions_european_instrument = "6B7TdBNAF7tWWz5sZbbBZj8jH1ix7QWAchtkvMHveEuW"
psyoptions_american_instrument = "HGmSFSRfVAG8RC8Ae4G1JFSHK7Au5GrGskDxncG3JRok"
hxro_print_trade_provider = "4WbVwc5Edfo3oB1n16bVC9qrghYHSNh1qAECbSCyiT95"
vault_operator = "5Qnp9VdXtRvmR9wBcAdvqTRsBHzpZ4jU3ZKtn3BaYWUM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-european-instrument/program",
    "hxro-print-trade-provider/program",
    "psyoptions-american-instrument/program",
    "vault-operator/program",
]

[scripts]
generate-test-fixtures = "yarn ts-node -T tests/scripts/fixturesGenerator.ts"
