[programs.localnet]
rfq = "669TjP6JkroCT5czWue2TGEPfcuFN8cz99Z1QMcNCWv7"
       
[programs.devnet]
rfq = "669TjP6JkroCT5czWue2TGEPfcuFN8cz99Z1QMcNCWv7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/convergence.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --reporter mocha-dd-reporter -t 1000000 tests/**/*.ts"