anchor_version = "0.25.0"

[programs.localnet]
rfq = "65Qqf1tMrjbummSS4eGEqsYC3WXWHo3EutVgiGvKbtG8"
risk_engine = "EdYHwN6v6vyJ2nigae2UT54JbNQKyoJJqBXnH2WPYZqR"
spot_instrument = "7g67fxoLsANj3HkHmuMhKPZ7nF45CPYvrVSB7dvtmJUM"
psyoptions_european_instrument = "4rdj5AwNUBqF8fV5tp54g3UXtJUGLZhwQCoPbvNFA4Nh"
psyoptions_american_instrument = "ATtEpDQ6smvJnMSJvhLc21DBCTBKutih7KBf9Qd5b8xy"

[programs.devnet]
rfq = "J2rDyo2NpZn4FQ5rGXmdwh3i2y1h11ynodYrrcUxfErq"
risk_engine = "9sEUmfZPhH8qVEoFmfdbJhKcfWP5LCCZfb2Cu7zffs4b"
spot_instrument = "826r9RA3AGHPas5E4DgbN9MpYa8gE2ZDUPUJW6GEZ3cT"
psyoptions_european_instrument = "94sxcX64yqe1s7zY2Hx8tEN8tqisK86dASfizAKkxK7A"
psyoptions_american_instrument = "2XYQhTq6k3anvDSdiQ6hyNyzLS3m4TbAgokVr8EGAPHf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/anonymous/.config/solana/id.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-american-instrument/program",
    "psyoptions-european-instrument/program"
]

[scripts]
psyoptions-american-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/integration/psyoptionsAmerican.spec.ts"