[programs.localnet]
rfq = "2NivPZeNtQ7B7vDBXNMCi9x3C9SWDvqCfiZNcDckB6hp"
risk_engine = "7VfhLs4yNYbpWzH1n1g8myKX4KGJnujoLMUnAqsr3wth"
spot_instrument = "EaTiAXD8QBVjKCTYmddt3HFbpCMCEtrxFurkyweWqnXN"
psyoptions_european_instrument = "3JFY9G2f34J8UmDSh97g9qayJYBoZ4z1J42R4rn6Uzqm"
hxro_instrument = "fZ8jq8MYbf2a2Eu3rYFcFKmnxqvo8X9g5E8otAx48ZE"

[programs.devnet]
rfq = "2NivPZeNtQ7B7vDBXNMCi9x3C9SWDvqCfiZNcDckB6hp"
risk_engine = "7VfhLs4yNYbpWzH1n1g8myKX4KGJnujoLMUnAqsr3wth"
spot_instrument = "EaTiAXD8QBVjKCTYmddt3HFbpCMCEtrxFurkyweWqnXN"
psyoptions_european_instrument = "3JFY9G2f34J8UmDSh97g9qayJYBoZ4z1J42R4rn6Uzqm"
hxro_instrument = "5Vhsk4PT6MDMrGSsQoQGEHfakkntEYydRYTs14T1PooL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/convergence-v2.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "hxro-instrument/program",
    "psyoptions-european-instrument/program",
]

[test]
startup_wait = 100000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "FUfpR31LmcP1VSbz5zDaM7nxnH55iBHkpwusgrnhaFjL"
[[test.validator.clone]]
address = "5AZioCPiC7uZ4zRmkKSg5nsb2A98RhmW89a1pMwiDoeT"
[[test.validator.clone]]
address = "GbA1vNKFzGQogorVNF4yWrU7mWdb1gKAMJCSmirEApXg"
[[test.validator.clone]]
address = "HyWxreWnng9ZBDPYpuYugAfpCMkRkJ1oz93oyoybDFLB"
[[test.validator.clone]]
address = "3ERnKTAEcXGMQkT9kkwAi5ECPmvpKzVfAvymV2Bc13YU"
[[test.validator.clone]]
address = "4Zwghg3tNaHZuzpQHDWA4mbSyoVrNEfvS765z7s4tNYd"
[[test.validator.clone]]
address = "rPnaqXrvo3aBMChVLywnVz6nykSfXwvBYu1Yz1p6crv"
[[test.validator.clone]]
address = "92wdgEqyiDKrcbFHoBTg8HxMj932xweRCKaciGSW3uMr"
[[test.validator.clone]]
address = "DevB1VB5Tt3YAeYZ8XTB1fXiFtXBqcP7PbfWGB71YyCE"
[[test.validator.clone]]
address = "9bZkeo1WavFs81sNuaaqKsfVLE8qdBKPBunRYQrwhtcb"
[[test.validator.clone]]
address = "HRN2jtzB9NrttYibXefVThwf7LocyVYKxoVMUSrZe52C"
[[test.validator.clone]]
address = "86V5ZKCjUzabYh7CmkRovpGxE9AKooeU6PyC4WdpyUJK"
[[test.validator.clone]]
address = "BFnmwPU9UPSXc2MWcYwXWMgqm87fc7ZsPyrG8hsqjDXJ"
[[test.validator.clone]]
address = "HLzQZ9DndaXkrwfwq8RbZFsDdSQ91Hufht6ekBSmfbQq"
[[test.validator.clone]]
address = "HYuv5qxNmUpAVcm8u2rPCjjL2Sz5KHnVWsm56vYzZtjh"
[[test.validator.clone]]
address = "VEpJVENzwhQDMj8MHPaP8UtAUvvDcdhfkqhXTPofoBG"
[[test.validator.clone]]
address = "BPFxey5mZm4bKHQQdFygBVbZjmpqESNPJ3zJjiYey19y"
[[test.validator.clone]]
address = "HovQMDrbAgAYPCmHVSrezcSmkMtXSSUsLDFANExrZh2J"
[[test.validator.clone]]
address = "GGMrh5gtGNjUcnK5Pk523PXNa4akN93ZrGvhJx7WGBnM"
[[test.validator.clone]]
address = "HsYYpmsZmhUrJDqbFjAuo6HPV9mygyWNTJ6g75a9KRR1"
[[test.validator.clone]]
address = "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"
[[test.validator.account]]
address = "8SXvChNYFhRq4EZuZvnhjrB3jJRQCv4k3P4W6hesH3Ee"
filename = "tests/dependencies/btc_20000_oracle_switchboard.json"
[[test.validator.account]]
address = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR"
filename = "tests/dependencies/sol_30_oracle_switchboard.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
