[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "hxro-instrument/program",
    "psyoptions-european-instrument/program",
]

[profile.release]
overflow-checks = true
